name = "SlottedRandomAccess"
uuid = "3cd48f03-9865-4243-ab2c-9fbbaa30d0d4"
authors = ["Alberto Mengali <disberd@gmail.com>"]
version = "0.1.0"

[deps]
Bumper = "8ce10254-0962-460f-a3d8-1f77fea1446e"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[weakdeps]
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"

[extensions]
PlotlyBaseExt = ["PlotlyBase"]

[compat]
Bumper = "0.6"
Distributions = "0.25"
DocStringExtensions = "0.9"
PlotlyBase = "0.8"
Polynomials = "4"
Random = "1"
StructArrays = "0.6"
julia = "1.10"